name: Windows - LiteManager RDP

on:
  workflow_dispatch:

jobs:
  build:
    name: Start LiteManager RDP
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Download & Install LiteManager
        run: |
          $url = "https://gitlab.com/chamod2/lm_win-10_github_rdp/-/raw/main/Downloads.bat"
          $output = "Downloads.bat"
          (New-Object System.Net.WebClient).DownloadFile($url, $output)
          Start-Process -FilePath "cmd.exe" -ArgumentList "/c Downloads.bat" -Wait

      - name: Start LiteManager
        run: Start-Process -FilePath "cmd.exe" -ArgumentList "/c LiteManager.bat" -Wait

      - name: Keep Session Active
        run: Start-Process -FilePath "cmd.exe" -ArgumentList "/c loop.bat" -Wait
